version: "3.6"

services:
    db:
        image: mariadb:10.8.2
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_volume:/var/lib/mysql"
        environment:
            MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MARIADB_DATABASE: ${MYSQL_DATABASE}
            MARIADB_USER: ${MYSQL_USER}
            MARIADB_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - ${DATABASE_PORT}:3306
        networks:
            - symfony
    php:
        build:
            context: .docker/php
            target: dev # you can use prod here to enable opcache & disable xdebug
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./application:/var/www/symfony/
        networks:
            - symfony
    nginx:
        build:
            context: .docker/nginx
        volumes:
            - ./application:/var/www/symfony/
        ports:
            - ${WEBSERVER_PORT}:80
            - ${WEBSERVER_PORT_SSL}:443
        networks:
            - symfony
        env_file:
            - .env

volumes:
    db_volume:

networks:
    symfony:
